### ISSUE TITLE
adding raster layer failing silently 

### ISSUE THREAD

**Issue by swatson26** [OpenGeoscience/geonotebook#155]
Hi,
Im having trouble getting the test raster to show up on the map while using geonotebook in docker. I have no error messages to work off of so would appreciate any help in debugging and tracking down the error source.  I've run `tox -e py27` with what seems to be no issue (see attached txt file).
[test_results.txt](https://github.com/OpenGeoscience/geonotebook/files/1424529/test_results.txt)

It seems like I'm able to successfully read in the geotiff
```
rd = RasterData('/notebooks/sandbox/watson/L57.Globe.month09.2010.hh09vv04.h6v1.doy247to273.NBAR.v3.0.tiff')
```
and `rd.uri` seems to function correctly, I  can also grab the resulting numpy array and plot it  inline with no issue

```
r = rd.get_data()
plt.imshow(r[:,:,3])
```
but when I `M.add_layer(rd, opacity=1.0, gamma=2.5)` nothing appears on the map. 

```
>>> M.layers[0].vis_url
'http://127.0.0.1:8888/ktile/410d71c3-f822-4804-bb00-a6f342ff7b12/L57.Globe.month09.2010.hh09vv04.h6v1.doy247to273.NBAR.v3.0_14105793776872957637'
``` 
and if I go that url:
```
{"__str__": "<TileStache.Core.Layer instance at 0x7ff1b4f9cea8>", "provider": {"opacity": 1.0, "colormap": [], "layer_srs": "+proj=longlat +datum=WGS84 +no_defs ", "is_static": false, "name": "L57.Globe.month09.2010.hh09vv04.h6v1.doy247to273.NBAR.v3.0_14105793776872957637", "filepath": "/notebooks/sandbox/watson/L57.Globe.month09.2010.hh09vv04.h6v1.doy247to273.NBAR.v3.0.tiff", "raster_x_size": 7243, "transform": [-123.06229313641593, 0.0007517610843588367, 0.0, 48.571429239198785, 0.0, -0.0007517610843588367], "vrt_path": "/tmp/geonbLODDc6/L57.Globe.month09.2010.hh09vv04.h6v1.doy247to273.NBAR.v3.0_14105793776872957637.vrt", "raster_y_size": 1900, "map_srs": "EPSG:4326", "nodata": -9999.0, "gamma": 2.5}}
```
Please let me know what additional info would be helpful in debugging this. 
Thanks!

**Comment by swatson26** [comment]
docker container was run `docker run -p 8888:8888 -v /path/to/your/notebooks:/notebooks  -it --rm geonotebook` 

and using default config 
```
[default]
vis_server = ktile
log_level = WARNING

[geoserver]
username = admin
password = geoserver
url = http://127.0.0.1:8080/geoserver

[ktile]
url = http://127.0.0.1:8888/ktile
default_cache = ktile_default_cache

[ktile_default_cache]
name = Test
path = /tmp/stache
umask = 0000
```

**Comment by dorukozturk** [comment]
Hey @swatson26 thanks for trying out Geonotebook. Actually your issue is the same as #155. I just created a [PR](https://github.com/OpenGeoscience/geonotebook/pull/156) and I think we can update our images on Dockerhub tomorrow. Fix was pretty trivial but took some time to figure out. The layer that you were adding was going behind the basemap. That is why you were not seeing any errors.

**Comment by swatson26** [comment]
Thanks! Im looking forward to continuing to use Geonotebook - love the concept

**Comment by dorukozturk** [comment]
@swatson26 We merged the fix and a new docker image should be built and pushed soon. Thanks for creating an issue !!! You can check it out [here](https://hub.docker.com/r/geonotebook/geonotebook/builds/).

**Comment by swatson26** [comment]
@dorukozturk I re-ran on the updated code and I'm still getting the same result 

not sure if this helps, but this is the map state I'm getting after adding a single raster layer and adding a rectangle. To the uniformed, the undefined zIndex for the annotation seems a bit odd

```
{'layers': {'layers': [{'name': 'L57.Globe.month09.2010.hh09vv04.h6v1.doy247to273.NBAR.v3.0_9853832725075006505',
    'query_params': {},
    'vis_options': {'attribution': None,
     'colormap': [],
     'gamma': 2.5,
     'interval': None,
     'kernel_id': u'e8607d71-0a2f-4b06-82b2-09d2d4dd693e',
     'layer_type': None,
     'opacity': 1.0,
     'projection': 'EPSG:3857',
     'zIndex': 0},
    'vis_url': 'http://127.0.0.1:8888/ktile/e8607d71-0a2f-4b06-82b2-09d2d4dd693e/L57.Globe.month09.2010.hh09vv04.h6v1.doy247to273.NBAR.v3.0_9853832725075006505'}],
  'system_layers': [{'annotations': [{'args': ([[-121.21894316854382,
         46.26798208448121],
        [-121.21894316854382, 48.47710148793778],
        [-116.00435638507162, 48.47710148793778],
        [-116.00435638507162, 46.26798208448121]],
       None),
      'kwargs': {'id': 4, 'name': 'Rectangle 4', 'rgb': '#b9db57'},
      'type': 'rectangle'}],
    'name': 'annotation',
    'query_params': {},
    'vis_options': {'attribution': None,
     'colormap': [],
     'gamma': 1.0,
     'interval': None,
     'kernel_id': u'e8607d71-0a2f-4b06-82b2-09d2d4dd693e',
     'layer_type': 'annotation',
     'opacity': 1.0,
     'projection': 'EPSG:3857',
     'zIndex': None},
    'vis_url': None}]}}
```

**Comment by dorukozturk** [comment]
@swatson26 I just pulled the latest image and tried some of the examples and they worked for me. Can you follow the steps below?

```
# Delete all geonotebook images you currently have
docker images | grep geonotebook | awk '{print $1}' | xargs docker rmi 

# Pull and run the latest geonotebook
docker run -p 8888:8888 -v /full/path/to/geonotebook/notebooks:/notebooks -it --rm geonotebook/geonotebook

**Comment by swatson26** [comment]
yep, user error on my part - thanks!
